
import {
  UploadCloud,
  FileText,
  Share2,
  ShieldAlert,
  Settings,
  LayoutDashboard,
  BookOpen,
  GitFork,
  Zap,
  Eye,
  FileJson,
  Globe,
  Loader2,
  ChevronRight,
  ChevronDown,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  ExternalLink,
  Server,
  Replace,
  PlusCircle,
  Trash2,
  Network,
  ArrowRightCircle,
  Edit3,
  Edit,
  Home, // Added Home
  ListChecks, // Added ListChecks
} from 'lucide-react';

export const Icons = {
  UploadCloud,
  FileText,
  Share2,
  ShieldAlert,
  Settings,
  LayoutDashboard,
  BookOpen,
  GitFork,
  Zap,
  Eye,
  FileJson,
  Globe,
  Loader: Loader2,
  ChevronRight,
  ChevronDown,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  ExternalLink,
  Server,
  HttpReplace: Replace,
  HttpPost: PlusCircle,
  HttpDelete: Trash2,
  HttpPatch: Edit,
  HttpGet: ArrowRightCircle, 
  Network,
  Home,
  ListChecks,
};

export const ApiMethodIcons: Record<string, React.ElementType> = {
  get: Icons.HttpGet,
  post: Icons.HttpPost,
  put: Icons.HttpReplace,
  delete: Icons.HttpDelete,
  patch: Icons.HttpPatch,
  options: Icons.Settings,
  head: Icons.Eye,
  trace: Icons.GitFork,
};
