
import {
  UploadCloud,
  FileText,
  Share2,
  ShieldAlert,
  Settings,
  LayoutDashboard,
  BookOpen,
  GitFork,
  Zap,
  Eye,
  FileJson,
  Globe,
  Loader2,
  ChevronRight,
  ChevronDown,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  ExternalLink,
  Server,
  Replace,
  PlusCircle,
  Trash2,
  Network,
  ArrowRightCircle, // Ensure ArrowRightCircle is imported
  Edit3,
  Edit,
  Home, 
  ListChecks,
  FilePlus2, 
  FileOutput,  
  Activity,    
  HeartPulse,  
  ShieldCheck, 
  Gavel,
  LogIn,
  LogOut,
  Cpu,
  MemoryStick,
  GaugeCircle,
  AlertOctagon,
  SlidersHorizontal,
  ClipboardList,
  Lightbulb,
  LineChart,
  PauseCircle,
  PlayCircle,
  RefreshCw,
  Maximize,
  Palette, 
  Search,
  Radar, 
  TrendingUp, 
  Webhook, 
  LocateFixed, 
  BrainCircuit, 
  Gauge, 
} from 'lucide-react';

export const Icons = {
  UploadCloud,
  FileText,
  Share2,
  ShieldAlert,
  Settings,
  LayoutDashboard,
  BookOpen,
  GitFork,
  Zap,
  Eye,
  FileJson,
  Globe,
  Loader: Loader2,
  ChevronRight,
  ChevronDown,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  ExternalLink,
  Server,
  HttpReplace: Replace,
  HttpPost: PlusCircle,
  HttpDelete: Trash2,
  HttpPatch: Edit,
  HttpGet: ArrowRightCircle, 
  ArrowRightCircle, // Add ArrowRightCircle here
  Network,
  Home,
  ListChecks,
  FilePlus2,
  FileOutput,
  Activity,
  HeartPulse,
  ShieldCheck,
  Gavel,
  LogIn,
  LogOut,
  Cpu,
  MemoryStick,
  GaugeCircle,
  AlertOctagon,
  SlidersHorizontal,
  ClipboardList,
  Lightbulb,
  LineChart,
  PauseCircle,
  PlayCircle,
  RefreshCw,
  Maximize,
  Palette,
  Search,
  Radar,
  TrendingUp,
  Webhook,
  LocateFixed,
  BrainCircuit,
  Gauge,
};

export const ApiMethodIcons: Record<string, React.ElementType> = {
  get: Icons.HttpGet,
  post: Icons.HttpPost,
  put: Icons.HttpReplace,
  delete: Icons.HttpDelete,
  patch: Icons.HttpPatch,
  options: Icons.Settings,
  head: Icons.Eye,
  trace: Icons.GitFork,
};

